# Generated by Django 5.0.2 on 2024-02-23 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название игры')),
                ('price', models.CharField(max_length=100, verbose_name='Цена на игру')),
                ('url', models.CharField(max_length=300, verbose_name='Ссылка на игру')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game', verbose_name='Любимая игра')),
            ],
        ),
    ]
