# Generated by Django 5.0.2 on 2024-03-17 12:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='price',
        ),
        migrations.AddField(
            model_name='game',
            name='new_price',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Новая цена'),
        ),
        migrations.AddField(
            model_name='game',
            name='old_price',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Старая цена'),
        ),
        migrations.AlterUniqueTogether(
            name='favoritegame',
            unique_together={('user', 'game')},
        ),
    ]
