# Generated by Django 5.0.5 on 2024-05-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_game_price_game_new_price_game_old_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='new_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Новая цена'),
        ),
        migrations.AlterField(
            model_name='game',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Старая цена'),
        ),
    ]
